# Generated by Django 5.2.8 on 2025-12-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
