# Generated by Django 5.2.8 on 2025-11-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppSetting',
            new_name='PlatformSetting',
        ),
    ]
