# Generated by Django 5.2.8 on 2025-11-22 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('docker_image', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('default_duration', models.PositiveIntegerField(default=1)),
                ('app_port_intern_web', models.PositiveIntegerField(default=80)),
                ('app_port_intern_api', models.PositiveIntegerField(default=1)),
                ('hiddenservice_port_web', models.PositiveIntegerField(default=80)),
                ('hiddenservice_port_api', models.PositiveIntegerField(default=1)),
                ('use_deploy_user', models.BooleanField(default=False, help_text='Container mit User {uid}:{gid} starten')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='RemoteHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('ssh_user', models.CharField(default='root', max_length=32)),
                ('ssh_key_path', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AppVolumePerApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_path', models.CharField(help_text='Pfad auf dem Host‑Dateisystem.', max_length=256)),
                ('container_path', models.CharField(help_text='Zielpfad im Docker‑Container.', max_length=256)),
                ('app', models.ForeignKey(help_text='Die App, für die dieses Volume definiert ist.', on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='paas.appdefinition')),
            ],
            options={
                'verbose_name': 'App‑Volume',
                'verbose_name_plural': 'App‑Volumes',
                'unique_together': {('app', 'host_path', 'container_path')},
            },
        ),
        migrations.CreateModel(
            name='ConfigPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_file', models.CharField(help_text='Pfad relativ zum Home‑Verzeichnis des Deploy‑Users', max_length=256)),
                ('pattern', models.CharField(help_text='Regulärer Ausdruck, der die zu bearbeitende Zeile identifiziert', max_length=256)),
                ('action', models.CharField(choices=[('comment', 'Zeile auskommentieren'), ('replace', 'Zeile ersetzen'), ('delete', 'Zeile löschen')], default='comment', max_length=8)),
                ('replacement', models.CharField(blank=True, help_text='Nur für “replace” nötig – der neue Zeilentext (ohne Zeilenumbruch)', max_length=512, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_patches', to='paas.appdefinition')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_patches', to='paas.appvolumeperapp')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, max_length=64, null=True)),
                ('container_name', models.CharField(blank=True, max_length=128, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('log', models.TextField(blank=True, null=True)),
                ('onion_address', models.CharField(blank=True, help_text='Onion‑Adresse des Tor‑Hidden‑Services (falls erstellt)', max_length=100, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paas.appdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paas.remotehost')),
            ],
        ),
        migrations.CreateModel(
            name='UserAppLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_apps', models.PositiveIntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_limit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User‑App‑Limit',
                'verbose_name_plural': 'User‑App‑Limits',
            },
        ),
        migrations.CreateModel(
            name='AppEnvVarPerApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
                ('optional', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_vars', to='paas.appdefinition')),
            ],
            options={
                'unique_together': {('app', 'key')},
            },
        ),
    ]
